### ISSUE TITLE
problem loading dseries from .m file

### ISSUE THREAD

**Issue by houtanb** [DynareTeam/dates#5]
The following ```.m``` file cannot be loaded by the ```dseries``` command, as it complains that the dimensions are not the same, even though they don't have to be
```
INIT__='3y';
NAMES__ = {'cons','robo'};
cons = randn(100,1);
robo = randn(50,1);
```

**Comment by stepan-a** [comment]
This is not a bug. All the variables must have the same number of observations  (with NaNs if some observations are missing). We could add automatically the NaNs at the end of the sample, but this would be a new feature...

**Comment by houtanb** [comment]
If it's not a bug, it is bizarre that we can do:
```
[dseries(randn(100,1),'3y','cons') dseries(randn(50,1),'3y','robo')];
```
but cannot load the same thing from a file. I will reopen this in ```dseries``` as it was mistakenly placed here.
